import Button from './From/Button';
import Div from './From/Div';
import Form from './From/Form';
import Input from './From/Input';
import Label from './From/Label';
import TextArea from './From/TextArea';
import AlertComp from './AlertComp';
import ModalComp from './ModalComp';
import NavComp from './NavComp';
import ProgresComp from './ProgresComp';
import SliderComp from './SliderComp';
module.exports = {Button,Div,Form,Input,Label,TextArea,ModalComp,NavComp,ProgresComp,SliderComp};
